# Generated by Django 2.1.3 on 2018-11-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='Username', max_length=16, verbose_name='Username')),
                ('e_mail', models.CharField(db_column='E-mail', max_length=50, verbose_name='E-mail')),
                ('nickname', models.CharField(db_column='Nickname', max_length=20, verbose_name='Nickname')),
                ('head_image', models.CharField(db_column='Head_image', max_length=10, verbose_name='Head_image')),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='Username', max_length=16, verbose_name='Username')),
                ('encrypt_value', models.CharField(db_column='Encrypt_value', max_length=200, verbose_name='Encrypt_value')),
                ('salt', models.CharField(db_column='Salt', max_length=20, verbose_name='Salt')),
            ],
        ),
    ]
